✨ Add transition_id method to BaseRecord
wecasa/zoho_hub pull request #9
Opened 2022-11-14 14:45 UTC by djulienwecasa

2022-11-15 08:49 UTC, wecasa-romain reviewed
Very nice idea i think, but you should also make a PR in the web repo that will reference the zoho_hub gem on this branch and fix everything that should break ?

2022-11-15 08:49 UTC, wecasa-romain commented on spec/zoho_hub/base_record_spec.rb
> +      test_instance.blueprint_transition('Closed', {})
```suggestion
      test_instance.blueprint_transition('Closed')
```
should work too?

2022-11-15 08:57 UTC, djulienwecasa commented
> Very nice idea i think, but you should also make a PR in the web repo that will reference the zoho_hub gem on this branch and fix everything that should break ?

Yes exactly, it's ongoing :)

2022-11-16 08:55 UTC, jlestavel requested changes

2022-11-16 08:55 UTC, jlestavel commented on lib/zoho_hub/base_record.rb
> +      raise "Unknown Account Blueprint transition: #{next_field_value}" unless transition
Can you please define an error class for this please?

2022-11-16 08:55 UTC, jlestavel commented on spec/zoho_hub/base_record_spec.rb
> +    end
```suggestion
    let(:test_instance) { described_class.new }
```

2022-11-16 08:55 UTC, jlestavel commented on spec/zoho_hub/base_record_spec.rb
> +      it 'correctly construct the record' do
```suggestion
      it 'correctly builds the record' do
```

2022-11-16 08:55 UTC, jlestavel commented on spec/zoho_hub/base_record_spec.rb
> +                   body: {}.to_json)
Couldn't we define those as `let!`?

2022-11-16 08:55 UTC, jlestavel commented on spec/zoho_hub/base_record_spec.rb
> +      allow(test_instance).to receive(:id).and_return('123456789')
Can't you set that during the `test_instance` definition? (`described_class.new(id: '123456789')`)

2022-11-16 08:55 UTC, jlestavel commented on spec/zoho_hub/base_record_spec.rb
> +      allow(described_class).to receive(:to_s).and_return('Leads')
Shouldn't you define a `test_class` instead? (like they do line 4)

2022-11-17 09:51 UTC, jlestavel approved these changes

2022-11-17 11:04 UTC, merged